Lk page mod
Largasson/SNT_project pull request #12
Opened 2023-12-26 08:16 UTC by FelixDS55

2023-12-28 01:52 UTC, skeapskeap requested changes

2023-12-28 01:52 UTC, skeapskeap commented on webapp/__init__.py
> +        number_area = area
выглядит ненужным

2023-12-28 01:52 UTC, skeapskeap commented on webapp/__init__.py
>          if area == 0:
это логично делать до похода в базу и до title= f'', короче в самом начале
а ещё лучше создать прямо роут @app.route('/user/0'), мы об этом говорили

2023-12-28 01:52 UTC, skeapskeap commented on webapp/__init__.py
> +        return render_template('lk_page.html', page_title=title, area=number_area,
Нет гарантии, что [0] - это именно последний по дате публикации. Нужно тогда делать order by в запросе. И если надо вытащить только первую строку выдачи, то в запросе же её и получать - first() вместо all()

2023-12-28 01:52 UTC, skeapskeap commented on webapp/loader.py
> +    with app.app_context():
with app.context() надо вытащить за пределы функции, она и так будет выполняться в контексте запущенного приложения

2023-12-28 01:52 UTC, skeapskeap commented on webapp/loader.py
> +        with open(filename, 'r', encoding='cp1251') as file:
открывание файла тоже не актуально для функции сохранения в базу, в логике вашего приложения она принимает res_dict аргументом

2023-12-28 01:52 UTC, skeapskeap commented on webapp/loader.py
> +            for item in my_list:
Можно же просто итерироваться по res_dict.values(). 
При повторном вызове save_data, в my_list останутся данные из первого вызова, и к ним добавятся данные из нового res_dict. И так он будет прирастать до бесконечности.

2023-12-28 01:52 UTC, skeapskeap commented on webapp/loader.py
> +                db.session.add(financial_data)
Т.к. обычно res_dict будет состоять из более чем 1 элемента, то лучше инсертить сразу всё одним запросом, это сильно быстрее.

2023-12-28 01:52 UTC, skeapskeap commented on webapp/loader.py
> +def save_data(filename):
save_data это самое популярное и самое непонятное имя для функции сохранения данных в БД. Хотелось бы понимать, какие именно данные сохраняет функция, и куда она их сохраняет. Возможно у тебя получится придумать лучше, чем у меня.
```suggestion
def insert_parsed_csv(financial_data: dict):
```

2023-12-28 01:52 UTC, skeapskeap commented on webapp/parsing_csv.py
>  class Error_csv_file(Exception):
В PEP8 принято специальное соглашение, как называть эксепшены.
```suggestion
class CsvFileError(Exception):
```

2023-12-28 01:52 UTC, skeapskeap commented on webapp/loader.py
> +app = create_app()
Всё, что не относится к обычной работе приложения - переносится в блок if __name__ == '__main__':

2023-12-28 14:27 UTC, FelixDS55 commented on webapp/__init__.py
> +        number_area = area
поправил

2023-12-28 14:27 UTC, FelixDS55 commented on webapp/__init__.py
> +        return render_template('lk_page.html', page_title=title, area=number_area,
Поправил

2023-12-28 14:27 UTC, FelixDS55 commented on webapp/loader.py
> +        with open(filename, 'r', encoding='cp1251') as file:
поправил

2023-12-28 14:27 UTC, FelixDS55 commented on webapp/loader.py
> +            for item in my_list:
поправил

2023-12-28 14:29 UTC, FelixDS55 commented on webapp/loader.py
> +def save_data(filename):
поправил

2023-12-28 14:29 UTC, FelixDS55 commented on webapp/parsing_csv.py
>  class Error_csv_file(Exception):
поправил

2023-12-28 14:32 UTC, FelixDS55 commented on webapp/loader.py
> +app = create_app()
поправил

2023-12-28 16:31 UTC, FelixDS55 commented on webapp/loader.py
> +                db.session.add(financial_data)
поправил

2023-12-29 09:15 UTC, skeapskeap commented on webapp/__init__.py
> +        info = FinancialData.query.filter(FinancialData.area_number == area).first()
Что будет если area не существует в БД? Например area = -1, или area=100500. Надо какую-то понятную ошибку пользователю возвращать. Добавьте таску в бэклог на потом.

2023-12-29 09:21 UTC, merged